# config/packages/liip_imagine.yaml
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: 'uploads/cache'

    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/public'
    
    twig:
        mode: lazy

    filter_sets:
        cache: ~
        
        status_thumb:
            quality: 100
            filters:
                thumbnail: { size: [500, 500], mode: outbound }
                
        status_thumb_api:
            quality: 100
            filters:
                thumbnail: { size: [400, 300], mode: outbound }
                
        slide_thumb:
            quality: 100
            filters:
                thumbnail: { size: [500, 300], mode: outbound }
                
        category_thumb:
            quality: 100
            filters:
                thumbnail: { size: [500, 500], mode: outbound }
                
        category_thumb_api:
            quality: 100
            filters:
                thumbnail: { size: [500, 500], mode: outbound }
                
        language_thumb:
            quality: 100
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
                
        language_thumb_api:
            quality: 100
            filters:
                thumbnail: { size: [100, 100], mode: outbound }

