security:
    # Password hashers configuration (auto)
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User provider configuration to load users from the database
    providers:
        app_user_provider:
            entity:
                class: App\UserBundle\Entity\User
                property: email
        users_in_memory: { memory: null }

    # Firewalls Configuration
    firewalls:
        # Public routes accessible without authentication
        dev:
            pattern:
                - ^/_profiler/
                - ^/_wdt/
                - ^/css/
                - ^/images/
                - ^/js/
            security: false
        
        assets:
            pattern: ^/(css|js|images)/
            security: false

        # Main firewall that applies to the whole application
        main:
            provider: app_user_provider
            pattern: ^/
            lazy: true
            form_login:
                login_path: app_login         # Route to display the login form
                check_path: app_login   # Route to handle the login form submission
                default_target_path: /  # Redirect after successful login (can be adjusted)
                failure_path: null

            stateless: false

            logout:
                path: app_logout              # Define the logout route
                target: /                      # Redirect to home page after logout (adjust as needed)

            remember_me:
                secret: '%kernel.secret%'      # Secret key for remember-me functionality (make sure to set kernel.secret in .env)
            # Access Control Rules
    access_control:
        # Public routes
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api/device/, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }


    # Access control to enforce authentication and roles
    


# Test environment configuration
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
