<?php

// src/Repository/CategoryRepository.php
namespace App\AppBundle\Repository;

use App\AppBundle\Entity\Category;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Category::class);
    }

    /**
     * Returns the number of Category rows in the database.
     *
     * @return int The number of rows
     */
    public function countCategories(): int
    {
        // Use QueryBuilder to count the rows
        $queryBuilder = $this->createQueryBuilder('c')
                             ->select('count(c)');

        // Return the single scalar result (count)
        return (int) $queryBuilder->getQuery()->getSingleScalarResult();
    }
}
