<?php

// src/Repository/CommentRepository.php

namespace App\AppBundle\Repository;

use App\AppBundle\Entity\Comment;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Comment::class);
    }

    /**
     * Returns the number of Comment rows in the database.
     *
     * @return int The number of rows
     */
    public function countComments(): int
    {
        // Use QueryBuilder to count the rows
        $queryBuilder = $this->createQueryBuilder('c')
                             ->select('count(c)');

        // Return the single scalar result (count)
        return (int) $queryBuilder->getQuery()->getSingleScalarResult();
    }
}