<?php

// src/Repository/DeviceRepository.php

namespace App\AppBundle\Repository;

use App\AppBundle\Entity\Device;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Device::class);
    }

    /**
     * Returns the number of Device rows in the database.
     *
     * @return int The number of rows
     */
    public function countDevices(): int
    {
        // Use QueryBuilder to count the rows
        $queryBuilder = $this->createQueryBuilder('d')
                             ->select('count(d)');

        // Return the single scalar result (count)
        return (int) $queryBuilder->getQuery()->getSingleScalarResult();
    }
}
