<?php

// src/Repository/SettingsRepository.php

namespace App\AppBundle\Repository;

use App\AppBundle\Entity\Settings;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Settings::class);
    }

    /**
     * Returns the number of Settings rows in the database.
     *
     * @return int The number of rows
     */
    public function countSettings(): int
    {
        // Use QueryBuilder to count the rows
        $queryBuilder = $this->createQueryBuilder('s')
                             ->select('count(s)');

        // Return the single scalar result (count)
        return (int) $queryBuilder->getQuery()->getSingleScalarResult();
    }
}
