media_index:
    path: /medias/
    controller: App\MediaBundle\Controller\MediaController::index

media_add:
    path: /medias/add
    controller: App\MediaBundle\Controller\MediaController::add

media_delete:
    path: /medias/delete/{id}
    controller: App\MediaBundle\Controller\MediaController::delete

api_media_delete:
    path: /api/medias/delete/{id}/{token}/
    controller: App\MediaBundle\Controller\MediaController::apiDelete

media_api_upload:
    path: /api/medias/upload/{token}/
    controller: App\MediaBundle\Controller\MediaController::apiUpload
